# Generated by Django 2.0 on 2017-12-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_folder_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='CardSet',
        ),
    ]
