# Generated by Django 2.0 on 2017-12-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171215_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='card_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.CardSet'),
            preserve_default=False,
        ),
    ]
