# Generated by Django 2.0 on 2018-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flashcard_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='history',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
