# Generated by Django 2.0 on 2018-01-08 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flashcard_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='last_trained_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last trained date'),
        ),
    ]
