# Generated by Django 2.0 on 2018-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_flashcard_last_trained_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='front_first',
            field=models.BooleanField(default=False),
        ),
    ]
