# Generated by Django 2.0 on 2018-04-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180123_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=2000)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CardSet')),
            ],
        ),
    ]
