# Generated by Django 2.0 on 2017-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flashcard_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.CharField(max_length=2000),
        ),
    ]
